export const COINGECKO_IDS:any = {
  "0G": "zero-gravity",
  "2Z": "zeta",
  APT: "aptos",
  BLUE: "bluefin",
  BNB: "binancecoin",
  BOME: "book-of-meme",
  BONK: "bonk",
  BTC: "bitcoin",
  CLOUD: "cloud",
  DOGE: "dogecoin",
  DRIFT: "drift-protocol",
  ENA: "ethena",
  ES: "escoin-token",
  ETH: "ethereum",
  HYPE: "hyperliquid",
  IO: "io",
  JTO: "jito-governance-token",
  JUP: "jupiter",
  KMNO: "kamino",
  LINK: "chainlink",
  MET: "metis-token",
  MON: "mon-protocol",
  ONDO: "ondo-finance",
  PENGU: "pudgy-penguins",
  PEPE: "pepe",
  POL: "polygon-ecosystem-token",
  PUMP: "pump-fun",
  PYTH: "pyth-network",
  RAY: "raydium",
  RENDER: "render-token",
  SEI: "sei-network",
  SHIB: "shiba-inu",
  SOL: "solana",
  SONIC: "sonic",
  STABLE: "stablecoin",
  STRK: "starknet",
  SUI: "sui",
  SWTCH: "switch-token",
  TRUMP: "official-trump",
  UNI: "uniswap",
  USDT: "tether",
  WEN: "wen-4",
  WIF: "dogwifcoin",
  WLFI: "world-liberty-financial",
  W: "wormhole",
  XPL: "plasma",
  XRP: "ripple",
  ZRO: "layerzero"
};


export const myMarkets = ["BTC","SOL","ETH"]